[package]
name = "rustylm"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/core",
    "crates/backend",
    "crates/runtime",
]

resolver = "2"

[features]
default = []
cuda = ["rustylm-backend/cuda"]

[dependencies]
rustylm-core = { path = "crates/core" }
rustylm-backend = { path = "crates/backend" }
rustylm-runtime = { path = "crates/runtime" }