[package]
name = "rustylm-runtime"
license = "MIT"
repository = "https://github.com/Kem0wow/rustylm"
version = "0.1.2"
edition = "2024"

[features]
default = []
cuda = ["rustylm-backend/cuda"]

[dependencies]
rustylm-core    = { path = "../core" }
rustylm-backend = { path = "../backend" }
anyhow          = "1.0"
rayon           = "1.10"